import type { Product } from "@/types";

export const products: Product[] = [
  // NEW ARRIVALS
  {
    id: "1",
    slug: "textured-knitted-shirt",
    name: "Textured Knitted Shirt",
    badge: "New",
    price: 5900,
    originalPrice: 7900,
    category: "shirts",
    gender: "mens",
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=80&auto=format&fit=crop",
    description: "A refined knitted shirt crafted from premium cotton blend. The textured weave adds depth and dimension to a timeless silhouette.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cream", "Sage", "Navy"],
  },
  {
    id: "2",
    slug: "structured-trench-coat",
    name: "Structured Trench Coat",
    badge: "New",
    price: 21000,
    originalPrice: 28000,
    category: "outerwear",
    gender: "womens",
    image: "https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=800&q=80&auto=format&fit=crop",
    description: "A contemporary trench coat with clean, architectural lines. Water-resistant shell with a belted waist for a polished silhouette.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Camel", "Black", "Ivory"],
  },
  {
    id: "3",
    slug: "mini-denim-overalls",
    name: "Mini Denim Overalls",
    badge: "New",
    price: 4500,
    originalPrice: 6000,
    category: "bottoms",
    gender: "womens",
    image: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&q=80&auto=format&fit=crop",
    description: "Playful mini overalls in washed denim. Adjustable straps and a relaxed bib front make this a weekend staple.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Light Wash", "Dark Wash"],
  },
  {
    id: "4",
    slug: "riviera-collar-shirt",
    name: "Riviera Collar Shirt",
    badge: "New",
    price: 4500,
    originalPrice: 6000,
    category: "shirts",
    gender: "mens",
    image: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80&auto=format&fit=crop",
    description: "Lightweight linen-blend shirt with a wide spread collar. Perfect for warm-weather dressing with effortless European style.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Sky Blue", "Terracotta"],
  },
  {
    id: "5",
    slug: "stretch-jersey-tee",
    name: "Stretch Jersey Tee",
    badge: "New",
    price: 6500,
    originalPrice: 9500,
    category: "tops",
    gender: "womens",
    image: "https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=800&q=80&auto=format&fit=crop",
    description: "Soft, form-fitting jersey tee with four-way stretch. Seamless construction for a clean, smooth finish.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Blush", "Charcoal"],
  },
  {
    id: "6",
    slug: "urban-utility-cargo",
    name: "Urban Utility Cargo",
    badge: "New",
    price: 9000,
    originalPrice: 12000,
    category: "bottoms",
    gender: "mens",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80&auto=format&fit=crop",
    description: "Technical cargo trousers with multiple utility pockets. Relaxed tapered fit crafted from durable ripstop fabric.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Olive", "Khaki", "Black"],
  },
  {
    id: "7",
    slug: "classic-boxy-tee",
    name: "Classic Boxy Tee",
    badge: "New",
    price: 3500,
    originalPrice: 4500,
    category: "tops",
    gender: "unisex",
    image: "https://images.unsplash.com/photo-1527719327859-c6ce80353573?w=800&q=80&auto=format&fit=crop",
    description: "An oversized boxy tee in heavyweight cotton. Dropped shoulders and a relaxed cut for effortless layering.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Black", "Stone", "Washed Grey"],
  },
  {
    id: "8",
    slug: "pleated-smart-trousers",
    name: "Pleated Smart Trousers",
    badge: "New",
    price: 7600,
    originalPrice: 10000,
    category: "bottoms",
    gender: "mens",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4b4799?w=800&q=80&auto=format&fit=crop",
    description: "Elegant pleated trousers with a wide-leg silhouette. Premium wool-blend fabric with a fluid drape.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Charcoal", "Cream", "Navy"],
  },
  {
    id: "9",
    slug: "french-terry-shorts",
    name: "French Terry Shorts",
    badge: "New",
    price: 4000,
    originalPrice: 5500,
    category: "bottoms",
    gender: "unisex",
    image: "https://images.unsplash.com/photo-1604176354204-9268737828e4?w=800&q=80&auto=format&fit=crop",
    description: "Relaxed lounge shorts in soft French terry. An elastic waist and drawstring for a comfortable, all-day fit.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Grey", "Oatmeal", "Black"],
  },
  // BEST SELLERS
  {
    id: "10",
    slug: "heavyweight-oversized-hoodie",
    name: "Heavyweight Oversized Hoodie",
    badge: "Best Seller",
    price: 8500,
    originalPrice: 11000,
    category: "tops",
    gender: "unisex",
    image: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&q=80&auto=format&fit=crop",
    description: "A wardrobe essential in 400GSM cotton fleece. Oversized fit with a kangaroo pocket and ribbed cuffs.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Oatmeal", "Washed Olive", "Slate Blue"],
  },
  {
    id: "11",
    slug: "patterned-knit-sweater",
    name: "Patterned Knit Sweater",
    badge: "Best Seller",
    price: 4500,
    originalPrice: 9000,
    category: "tops",
    gender: "womens",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80&auto=format&fit=crop",
    description: "A cosy intarsia-knit sweater with a modern geometric pattern. Relaxed boxy fit in a soft merino blend.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cream/Brown", "Navy/White"],
  },
  {
    id: "12",
    slug: "quilted-bomber-jacket",
    name: "Quilted Bomber Jacket",
    badge: "Best Seller",
    price: 14500,
    originalPrice: 18000,
    category: "outerwear",
    gender: "mens",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80&auto=format&fit=crop",
    description: "A statement bomber jacket in quilted satin. Clean lines and a slim silhouette make this a modern classic.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Midnight Navy", "Sage"],
  },
  {
    id: "13",
    slug: "hooded-puffer-vest",
    name: "Hooded Puffer Vest",
    badge: "Best Seller",
    price: 4500,
    originalPrice: 7500,
    category: "outerwear",
    gender: "unisex",
    image: "https://images.unsplash.com/photo-1614676471928-2ed0ad1061a4?w=800&q=80&auto=format&fit=crop",
    description: "A lightweight hooded vest with premium down-alternative fill. Versatile layering piece for transitional weather.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Olive", "Stone"],
  },
  {
    id: "14",
    slug: "vegan-leather-leggings",
    name: "Vegan Leather Leggings",
    badge: "Best Seller",
    price: 7500,
    originalPrice: 9900,
    category: "bottoms",
    gender: "womens",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80&auto=format&fit=crop",
    description: "High-waisted leggings in buttery vegan leather. A second-skin fit with a concealed waistband.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black"],
  },
  {
    id: "15",
    slug: "cropped-boxy-blazer",
    name: "Cropped Boxy Blazer",
    badge: "Best Seller",
    price: 13000,
    originalPrice: 17500,
    category: "outerwear",
    gender: "womens",
    image: "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=800&q=80&auto=format&fit=crop",
    description: "A cropped single-button blazer with an oversized, structured silhouette. Lined in smooth satin.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Camel", "Chalk"],
  },
];

export const newArrivals = products.filter((p) => p.badge === "New");
export const bestSellers = products.filter((p) => p.badge === "Best Seller");

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, count = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && (p.category === product.category || p.gender === product.gender))
    .slice(0, count);
}

export function formatPrice(cents: number): string {
  return `$${(cents / 100).toFixed(2)}`;
}
